### ISSUE TITLE
Land Ownership Tokenization

### ISSUE THREAD

**Issue by chexware** [bit-country/Metaverse-Network#161]
Tokenize each land block as an NFT. Whoever owns each land NFT will be its owner.

Types
--
## New Types
  - Enums: 
     - OwnerId
         - Token (AssetId)
         - AccountId
         
Estate Pallet Changes 
--
- Storage
   - EstateOwner doubleMap(OwnerId,EstateId) => () 
- Calls
   -  mint_estate: the beneficiary will be OwnerId instead of AccountId; add implementation that covers the case in which the OwnerId is Token(AssetId)
   -  create_estate : the beneficiary will be OwnerId instead of AccountId; add implementation that covers the case in which the OwnerId is Token(AssetId)
   -  transfer_estate: add implementation for transfering the estate NFT if OwnerId is Token(AssetId)
   -  dissolve_estate: add implementation for burning the estate NFT if OwnerId is Token(AssetId)

**Comment by chexware** [comment]
@justinphamnz Do we want to tokenize both lands and estates or estates only?

**Comment by justinphamnz** [comment]
> @justinphamnz Do we want to tokenize both lands and estates or estates only?

Thanks @chexware. Ideally for both.

**Comment by justinphamnz** [comment]
In term of implementation of the change from AccountId to TokenId, we only need tokenize function to cover AccountId to Token
