### ISSUE TITLE
Scale codec deserialization error with v0.0.12

### ISSUE THREAD

**Issue by Poggi-Luca** [bit-country/Metaverse-Network#242]
Hello Bit.Country Team,
I'm Luca from :ice_cube: Iceberg Nodes :ice_cube: a Pioneer permissionless collator.

I'm getting this error when I try to start the node with the last version v0.0.12:
`Error: Service(Other("Scale codec deserialization error: IncompatibleColumnConfig { id: 4, reason: \"Column config mismatch. Expected \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: true\\\", got \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: false\\\"\" }"))`

I compiled the source code using the nightly version (stable doesn't work):
```
stable-x86_64-unknown-linux-gnu unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.66.0-nightly (a24a020e6 2022-10-18)
```

Build command: `cargo +nightly build --release --features=with-pioneer-runtime`

No issue with v0.0.11 which I'm running from several weeks, but I would like to update the node to the latest version.

Another info: I'm using `paritydb` database both for parachain and relaychain databases

Thank you for your support

**Comment by chexware** [comment]
Hi,

We manage to build the successfully on our end using the **nightly-2022-05-11** version of rust (1.62).
Try  running the following setup:

>   rustup default nightly && rustup update
>   rustup update nightly-2022-05-11
>   rustup update stable
>   rustup target add wasm32-unknown-unknown --toolchain nightly-2022-05-11
>   rustup default nightly-2022-05-11

Let us know if you still cannot build the node after that.

**Comment by Poggi-Luca** [comment]
Hi, thank you for the kind reply.

I tried to build using the suggested setup (as above), the build was successful (also before with other setup) but the same issue remain when we launch the node: `Error: Service(Other("Scale codec deserialization error: IncompatibleColumnConfig { id: 4, reason: \"Column config mismatch. Expected \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: true\\\", got \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: false\\\"\" }"))`

The issue is not related to building but when the node is started

**Comment by justinphamnz** [comment]
> Hi, thank you for the kind reply.
> 
> I tried to build using the suggested setup (as above), the build was successful (also before with other setup) but the same issue remain when we launch the node: `Error: Service(Other("Scale codec deserialization error: IncompatibleColumnConfig { id: 4, reason: \"Column config mismatch. Expected \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: true\\\", got \\\"preimage: false, uniform: false, refc: false, compression: 0, ordered: false\\\"\" }"))`
> 
> The issue is not related to building but when the node is started

Could you please share your command how did you run the node?
