### ISSUE TITLE
Locking mechanism to prevent asset transfer while on Auction

### ISSUE THREAD

**Issue by justinphamnz** [bit-country/Metaverse-Network#55]
Auction will finalize anyway but would be less confused if asset should not transferred while on Auction.

**Comment by mikejamesli** [comment]
As discussed @justinphamnz, i'll be taking a shot at this issue

**Comment by mikejamesli** [comment]
@justinphamnz PR here: https://github.com/bit-country/Bit-Country-Blockchain/pull/87
