### ISSUE TITLE
Bit Country community token traits

### ISSUE THREAD

**Issue by justinphamnz** [bit-country/Metaverse-Network#66]
Similar to multiple currencies traits but limited functionality to bit country scope and extendable to EVM and Pallet Contract.

**Comment by ed-iv** [comment]
working on this one

**Comment by ed-iv** [comment]
Hey @justinphamnz, after putting some thought into this, wondering if you could elaborate a bit more on what we're looking to do here to make sure I'm on the right track. How do you see these traits being used and what requirements do they need to meet to work w/ EVM & Pallet Contract?

Are we looking to replace current orml dependencies relating to tokens with something more tailored to bc needs?
